<div class="container-fluid topbar-container">
  <div class="row text-center center top-row">
    <div class="col-sm-offset-4 col-sm-4">
      <a href="http://test.paddison.co.uk" target="_blank"><img class="headerImage" src="imgs/logo.png" alt=""></a>
    </div>
    <div class="col-sm-4 text-right">
      <h4 class="space-right"><i class="fa font-awesome-color fa-phone" aria-hidden="true"></i> 0800 0699906 &nbsp;
      <a href="https://portal.wildanet.com" target="_blank"><i class="fa font-awesome-color fa-sign-out" aria-hidden="true"></i> SIGN IN</a></h4>
    </div>
  </div>
  <div class="row center second-set whiteHoverOrange">
    <div class="col-sm-4 space-left">
      <p>&nbsp;&nbsp;
        <!-- <i class="fa fa-chevron-left"></i> BACK &nbsp;  -->
        <span id="exitStrat"><i class="fa fa-times"></i> EXIT</span></p>
    </div>
    <div class="col-sm-8 text-right">
      <p>
        <span class="navvers" id="nav-about">1. ABOUT YOU&nbsp;&#124;</span>
        <span class="navvers" id="nav-area">2. AREA CHECKER&nbsp;&#124;</span>
        <span class="navvers" id="nav-result">3. RESULTS&nbsp;&#124;</span>
        <span class="navvers" id="nav-package">4. CHOOSE PACKAGE&nbsp;&#124;</span>
        <span class="navvers" id="nav-payment">5. PAYMENT&nbsp;&#124;</span>
        <span class="navvers" id="nav-install">6. INSTALL DATE&nbsp;&#124;</span>
        <span class="navvers" id="nav-done">7. ALL DONE&nbsp;</span>
      </p>
    </div>
  </div>
</div>
