<div class="giveMeTopShadow row center">
  <div class="col-sm-12">
    <div class="row">
      <div class="col-sm-3 giveMePaddingImages">
        <a href="http://test.paddison.co.uk" target="_blank"><img class="imagedivbottom" src="imgs/logo.png" alt=""></a>
        <a href="http://www.ukwispa.org/" target="_blank"><img class="icons" src="imgs/wispa.png" alt=""></a>
      </div>

      <div class="blueOrangeLink col-sm-6 text-left">
        <h4>Wildanet is an independent internet provider, bringing experience and expertise in fixed-wireless solutions to the region. Our lightning fast, reliable broadband internet services are built around proven and current network technologies, designed to create new options and providing for the first time, awesome choices to rural communities.</h4>
        <div class="row text-center">
          <div class="col-sm-3">
            <a href="http://test.paddison.co.uk/terms">T&Cs</a>
          </div>
          <div class="col-sm-3">
            <a href="http://test.paddison.co.uk/fair">Fair Use Policy</a>
          </div>
          <div class="col-sm-3">
            <a href="http://test.paddison.co.uk/acceptable">Acceptable Use Policy </a>
          </div>
          <div class="col-sm-3">
            <a href="http://test.paddison.co.uk/privacy">Privacy Policy </a>
          </div>
        </div>
      </div>
      <div class="blueOrangeLink col-sm-2 col-sm-offset-1 text-left">
        <h4 class="social">
          <a href="https://www.facebook.com/wildanetUK/" target="_blank"><i class="fa font-awesome-color fa-facebook-f"></i></a> &nbsp;
          <a href="https://twitter.com/wildanet" target="_blank"><i class="fa font-awesome-color fa-twitter"></i></a> &nbsp;
          <a href="https://www.linkedin.com/company/wildanet/" target="_blank"><i class="fa font-awesome-color fa-linkedin" aria-hidden="true"></i></a>&nbsp;
          <a href="https://www.instagram.com/wildanet/" target="_blank"><i class="fa font-awesome-color fa-instagram" aria-hidden="true"></i></a>&nbsp;
          <a href="https://plus.google.com/104683758438912949678" target="_blank"><i class="fa font-awesome-color fa-google-plus"></i></a>
        </h4>
        <h4><i class="fa font-awesome-color fa-phone" ></i> 0800 0699906</h4>
        <h4><a class="" href="mailto:hello@test.paddison.co.uk" target="_top"><i class="fa font-awesome-color fa-envelope" ></i> hello@test.paddison.co.uk</a></h4>
        <!--<h4><i class="fa font-awesome-color fa-sign-out" ></i> SIGN IN</h4>-->
      </div>
    </div>
    <div class="row copyRightBlock text-mini text-left">
      <div class="col-sm-6 col-sm-offset-3">
        <p>&copy;	Wildanet Limited 2018. Goonhilly Earth Station, Goonhilly Downs, Helston, TR12 6LQ Registered in England and Wales no 10586466. Members of UK WISPA and RIPE</p>
      </div>
    </div>
  </div>
</div>
